name: CMake

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
    - name: Setup environment
      run: apt update && apt install -y --no-install-recommends ca-certificates cmake git ninja-build g++ pkgconf libsystemd-dev libwayland-dev libxkbcommon-dev zlib1g-dev libssl-dev libasound2-dev libpulse-dev libcups2-dev libpcsclite-dev libavcodec-dev libpkcs11-helper1-dev
      
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
      
    - name: Output
      run: ls -R ${{github.workspace}}/build
