name: CMake

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
    - name: Setup environment
      run: apt update && apt install -y --no-install-recommends ca-certificates cmake git ninja-build g++ pkgconf xsltproc docbook-xsl libusb-1.0-0-dev libfuse3-dev libcjson-dev libsdl2-dev libsdl2-ttf-dev libsystemd-dev libx11-dev libicu-dev libwayland-dev libxkbcommon-dev zlib1g-dev libssl-dev libasound2-dev libpulse-dev libcups2-dev libpcsclite-dev libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavutil-dev libpostproc-dev libswresample-dev libswscale-dev libpkcs11-helper1-dev krb5-multidev heimdal-multidev
      
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=Release -DWITH_FFMPEG=ON -DWITH_WAYLAND=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
      
    - name: Install
      run: cmake --install ${{github.workspace}}/build

    - name: Package
      run: tar cvzf freerdp.tar.gz /usr/local
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Freerdp Bookworm
        path: freerdp.tar.gz
